# backend/alembic/script.py.mako

"""Final schema

Revision ID: d8b27011c72b
Revises: 
Create Date: 2025-10-03 09:43:58.277413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b27011c72b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_design_iterations_id'), table_name='design_iterations')
    op.drop_index(op.f('ix_design_iterations_prompt'), table_name='design_iterations')
    op.drop_table('design_iterations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('design_iterations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sketch_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generated_image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('narrative', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('compliance_check', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('design_iterations_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('design_iterations_pkey'))
    )
    op.create_index(op.f('ix_design_iterations_prompt'), 'design_iterations', ['prompt'], unique=False)
    op.create_index(op.f('ix_design_iterations_id'), 'design_iterations', ['id'], unique=False)
    # ### end Alembic commands ###